### ISSUE TITLE
Error loading entity data

### ISSUE THREAD

**Issue by heguangyong** [moqui/moqui-framework#152] opened 2016-11-24 10:48 UTC
following this step,caused en error . in macos, oracle jdk 1.8.0_77
 
1. $ ./gradlew build
2. $ ./gradlew load
3. $ ./gradlew getComponent -Pcomponent=HiveMind
4. $ ./gradlew load

18:41:18.085  WARN RequireNewTx      o.moqui.i.c.TransactionFacadeImpl Transaction rollback. The rollback was originally caused by: Error loading entity data
org.xml.sax.SAXException: Found element [mantle.ledger.LedgerServices.initPartyAccountingConfiguration] name, transformed to [mantle.ledger.LedgerServices.initPartyAccountingConfiguration], that is not a valid entity name or service name (line 143)
        at org.moqui.impl.entity.EntityDataLoaderImpl$EntityXmlHandler.startElement(EntityDataLoaderImpl.groovy:597) ~[moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:195) ~[?:1.8.0_77]
        at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:298) [moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.doCall(EntityDataLoaderImpl.groovy:273) [moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.call(EntityDataLoaderImpl.groovy) [moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.doCall(TransactionFacadeImpl.groovy:196) [moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.call(TransactionFacadeImpl.groovy) [moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at groovy.lang.Closure.run(Closure.java:495) [moqui_temp5801762064476253875WEB-INF_lib_groovy-2.4.7.jar.:2.4.7]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
18:41:18.092  WARN RequireNewTx      o.moqui.i.c.TransactionFacadeImpl Transaction rollback for [Error loading entity data]. Here is the current location: 
org.moqui.BaseException: Rollback location
        at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:426) ~[moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:409) ~[moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:342) ~[moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.doCall(EntityDataLoaderImpl.groovy:273) ~[moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.doCall(TransactionFacadeImpl.groovy:196) ~[moqui_temp6519423892254014360WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Error loading data: org.moqui.BaseException: Error loading entity data from file:/Users/fustic/Workspace/workspace-moqui/moqui-framework/runtime/component/mantle-udm/data/ZbaOrganizationDemoData.xml
org.moqui.BaseException: Error loading entity data from file:/Users/fustic/Workspace/workspace-moqui/moqui-framework/runtime/component/mantle-udm/data/ZbaOrganizationDemoData.xml
        at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:343)
        at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.doCall(EntityDataLoaderImpl.groovy:273)
        at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.doCall(TransactionFacadeImpl.groovy:196)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXException: Found element [mantle.ledger.LedgerServices.initPartyAccountingConfiguration] name, transformed to [mantle.ledger.LedgerServices.initPartyAccountingConfiguration], that is not a valid entity name or service name (line 143)
        at org.moqui.impl.entity.EntityDataLoaderImpl$EntityXmlHandler.startElement(EntityDataLoaderImpl.groovy:597)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
        at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:298)
        ... 3 more

**Comment by jonesde** [comment] 2016-11-24 19:51
Does this happen consistently or are you seeing it intermittently? I tried the steps you mentioned from a clean clone of moqui-framework and could not reproduce the issue. BTW, it is not necessary to run './gradlew build' before './gradlew load' because load depends on build but I tried that anyway when trying to reproduce this issue.

The error is that it is not finding the service (which is in mantle-usl), ie mantle.ledger.LedgerServices.initPartyAccountingConfiguration, which is a valid service name.

**Comment by jonesde** [comment] 2016-11-24 19:53
BTW, which version of Java are you using? Is it Oracle or OpenJDK? You can see this by running 'java -varsion'. I generally test on both Oracle JDK and OpenJDK, using a recent version of 1.8.

**Comment by jonesde** [comment] 2016-11-25 00:17
This looks like an intermittent issue I've seen a couple of times and that another developer I work with has seem. It only happens with the dev conf (used with gradle load and gradle test) and appears to be caused by a concurrency issue with cache timeout and reload in another thread when checking to see if a service exists. This should be fixed in commit #da8ddf1.

If this is something you can consistently reproduce please test and let me know how it goes. I've been unable to reproduce this in any consistent way (happens very rarely), but in theory these changes should help and with only minimal overhead.

Note that this would only happen with the dev configuration (not in production), unless the service definition (service.location) cache is manually cleared and the timing is just right with another thread.

**Comment by heguangyong** [comment] 2016-11-25 01:19
I am not sure,wheather this problem cause by install step.
1.$ ./gradlew build
2.$ ./gradlew load
3.$ ./gradlew getComponent -Pcomponent=HiveMind
4.$ ./gradlew load

**Comment by jonesde** [comment] 2016-11-25 09:15
It looks like you are running load twice on the same database. The gradle load task loads all data including seed-initial, install, and demo data that is only meant to be loaded once. I wouldn't expect this error message from doing that, but you would get others.

Do you get errors if you do just the moqui-framework download or clone, then run gradle getComponent and then gradle load?

Also which version of Moqui are you using and how are you downloading it?

**Comment by heguangyong** [comment] 2016-11-25 09:24
I use the trunk.
after I remove and clone a new copy,every run ok. the error is gone.

**Closed** 2016-11-25 09:30 UTC
