### ISSUE TITLE
Strange MySQL deadlock

### ISSUE THREAD

**Issue by aabiabdallah** [moqui/moqui-framework#279] opened 2017-11-14 19:48 UTC
I have encountered a very strange lock with Moqui 2.1 connected to MySQL 5.7. SQL statements to insert into USER_LOGIN_KEY are getting queued with LOCK WAIT status. They're all waiting for a lock on the USER_ACCOUNT table. The lock doesn't have any query so its difficult to identify:

`SELECT 
    lck.lock_id, 
    lck.lock_mode, 
    lck.lock_table, 
    lck.lock_index, 
    trx.trx_id,
    trx.trx_mysql_thread_id,
    trx.trx_started, 
    trx.trx_state, 
    trx.trx_isolation_level,
    trx.trx_query,
    trx.trx_requested_lock_id,
    trx.trx_tables_locked,
    trx.trx_autocommit_non_locking
FROM 
    innodb_locks lck, 
    innodb_trx trx
WHERE 
    lck.lock_trx_id=trx.trx_id\G;`

And the result:

                   lock_id: 4239118:40:72:58
                 lock_mode: X
                lock_table: `moqui`.`user_account`
                lock_index: PRIMARY
                    trx_id: 4239118
       trx_mysql_thread_id: 241
               trx_started: 2017-11-14 20:16:51
                 trx_state: RUNNING
       trx_isolation_level: READ COMMITTED
                 trx_query: NULL
     trx_requested_lock_id: NULL
         trx_tables_locked: 1

I checked the moqui logs and found an error at the exact time the lock was created.

--- 2017-11-14 20:17:51.236 [-task-scheduler] WARN                     bitronix.tm.BitronixTransaction []
 transaction timed out: a Bitronix Transaction with GTRID [31302E3130302E31302E39310000015FBB88942700063D6E], status=MARKED_ROLLBACK, 1 resource(s) enlisted (started Tue Nov 14 20:16:51 AST 2017)

This is causing inserts to USER_LOGIN_KEY to queue up, consume all allowed SQL connections, and eventually crash MySQL.

Any clues?

**Comment by jonesde** [comment] 2017-11-15 06:54
The first step for anything like a lock that won't go away is to track down the lock, that is the real issue so that's what needs to be fixed. The log message you found may be a good place to start if you can't get any more info from the database (such as queries so far in the tx with the lock, I haven't looked into MySQL to see if/how one might do that). There should be other error messages before or around that, but at least the timeout bit is a good clue. For a transaction to time out it would need to go for > 60 seconds (with default settings anyway), so you'd want to review the log for the previous minute or so to see what the system was doing (screens rendering, any info about services running, etc).

Any thoughts on how I might reproduce this, ie based on the running scenario where you saw this? Was it in a test of some sort, or in a production instance?

Also, which version of Moqui Framework are you running (release or last pull date or commit #)?

Without tracking down the query (or possible candidate queries) that caused the lock on user_account it's hard to even guess at the cause. I haven't seen anything like this in production or load test runs , but that doesn't mean there isn't an issue in the framework code that is causing this. However, it may be in custom code running in the framework and if that's the case any attempt to reproduce it with the stock framework and application code and such would fail to find anything.

**Comment by jonesde** [comment] 2017-11-15 07:01
BTW, is this really a deadlock? That means circular locks, and generally the DB will detect those or they'll time out, and if you're lucky you'll get an error message saying it is a circular/dead lock. It could also be a transaction that is very long running (long tx timeout, some OOTB services even have these) that is holding the lock, and the log message with the tx timeout error could be a different transaction.

Another thought: if this is intermittent and on a production server sometimes the best thing to do is strategically add log messages such as all tx begin, commit, rollback, etc operations with condensed stack traces or artifact stacks (from the ArtifactExecutionFacade). If you are running a recent version of the moqui-elasticsearch component you'll have logging to ElasticSearch and access to it in the System app's Log Viewer, and that is really handy for searching and browsing log messages.

I also recall a change a few months ago to the UserLoginHistory to avoid locking issues, but I don't remember the details. If you are running an older version of moqui-framework that change could help avoid the lock waits for UserLoginHistory, even if there is still an issue with a long-lived lock on UserAccount... though that should still be looked into.

**Comment by aabiabdallah** [comment] 2017-11-16 16:20
Here are the facts I have today:

- The environment is production with 16K users, most of which use REST APIs.
- The environment is based on a pull version (I'll update with the commit#)
- There is not deadlock per say. A connection with no query (seems like a rollback) is getting executed and never finishes. Other connections are getting stuck in LOCK WAIT state waiting for it to complete.

The scenario causing this behavior is not consistent, i.e. it is not happening every time. 

1. It starts with a call to the /login service (see below) with wrong credentials. 
2. Followed by another call to the same service with correct credentials. 
3. Boom!
4. I was not able to reproduce this behavior. I must have tried it more than 50 times.

`
<service verb="login" noun="User" type="inline">
    <in-parameters/>
    <out-parameters>
        <parameter name="apiKey" type="String"/>
    </out-parameters>
    <actions>
        <script>result.put("apiKey", ec.user.loginKey)</script>
    </actions>
</service>
`

I'm keeping a close eye on the environment and will share detailed logs in the issue pops up again.

**Comment by jonesde** [comment] 2017-11-17 09:54
This statement doesn't make sense: "A connection with no query (seems like a rollback) is getting executed and never finishes." How would a connection with no query get a lock?

**Comment by aabiabdallah** [comment] 2017-11-17 11:13
This is puzzling me too. In my first post I ran a SQL query to see the locks and transactions and the one that would'nt finish had trx_query: NULL. I could see the queries of all other transactions in LOCK WAIT state but not this one.

**Comment by jonesde** [comment] 2017-12-13 06:16
Any updates on this? Just reviewing open issues and saw this is still outstanding. If not I'll close it.

**Comment by aabiabdallah** [comment] 2017-12-14 07:00
I've managed to trace a sequence of actions this, however it seems to be completely random. I'm not sure if it is related to MySQL or Bitronix.

**Step 1:** 
User inputs incorrect credentials. The system behaves as expected and throws the IncorrectCredentialsException:

```
org.apache.shiro.authc.IncorrectCredentialsException: Username xxx@gmail.com and/or password incorrect
	at org.moqui.impl.util.MoquiShiroRealm.getAuthenticationInfo(MoquiShiroRealm.groovy:207) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingleRealmAuthentication(ModularRealmAuthenticator.java:180) ~[shiro-core-1.4.0.jar:1.4.0]
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:267) ~[shiro-core-1.4.0.jar:1.4.0]
	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) ~[shiro-core-1.4.0.jar:1.4.0]
	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) ~[shiro-core-1.4.0.jar:1.4.0]
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:274) ~[shiro-core-1.4.0.jar:1.4.0]
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:260) ~[shiro-core-1.4.0.jar:1.4.0]
	at org.moqui.impl.context.UserFacadeImpl.loginUser(UserFacadeImpl.groovy:439) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
	at org.moqui.impl.context.UserFacadeImpl.initFromHttpRequest(UserFacadeImpl.groovy:111) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
	at org.moqui.impl.context.ExecutionContextImpl.initWebFacade(ExecutionContextImpl.java:176) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
	at org.moqui.impl.webapp.MoquiServlet.service(MoquiServlet.groovy:92) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.14]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.14]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.14]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.14]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [catalina.jar:8.5.14]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.14]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [catalina.jar:8.5.14]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) [catalina.jar:8.5.14]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.14]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.14]
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:486) [tomcat-coyote.jar:8.5.14]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.14]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-coyote.jar:8.5.14]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-coyote.jar:8.5.14]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.14]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.14]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

Then it attempts to rollback the transaction. This rollback is somehow causing an issue:

```
org.moqui.BaseException: Rollback location
	at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:434) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
	at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:409) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
	at org.moqui.impl.screen.ScreenRenderImpl.internalRender(ScreenRenderImpl.groovy:341) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
	at org.moqui.impl.screen.ScreenRenderImpl.render(ScreenRenderImpl.groovy:145) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
	at org.moqui.impl.webapp.MoquiServlet.service(MoquiServlet.groovy:96) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.14]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.14]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.14]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.14]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [catalina.jar:8.5.14]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.14]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [catalina.jar:8.5.14]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) [catalina.jar:8.5.14]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.14]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.14]
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:486) [tomcat-coyote.jar:8.5.14]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.14]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-coyote.jar:8.5.14]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-coyote.jar:8.5.14]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.14]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.14]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Step 2:**
User inputs correct credentials and system attempts to generate a login key for him. This hangs in lock wait state. And so does any future attempt for this user unless we manually kill the statement holding the lock (second statement below in this case).

                   lock_id: 4691782:40:239:92
                 lock_mode: S
                lock_table: `moqui`.`user_account`
                lock_index: PRIMARY
                    trx_id: 4691782
       trx_mysql_thread_id: 19400
               trx_started: 2017-11-21 06:01:04
                 trx_state: LOCK WAIT
       trx_isolation_level: READ COMMITTED
                 trx_query: INSERT INTO USER_LOGIN_KEY (LOGIN_KEY, USER_ID, FROM_DATE, THRU_DATE, LAST_UPDATED_STAMP) VALUES ('cfd496ac90791715a8e7d5539ea259bf110daf6d8335f68ad27c484237e54f73', '111315', '2017-11-21 06:01:04.811', '2017-11-27 06:01:04.811', '2017-11-21 06:01:04.811')
     trx_requested_lock_id: 4691782:40:239:92
         trx_tables_locked: 2

                   lock_id: 4691781:40:239:92
                 lock_mode: X
                lock_table: `moqui`.`user_account`
                lock_index: PRIMARY
                    trx_id: 4691781
       trx_mysql_thread_id: 19386
               trx_started: 2017-11-21 06:01:04
                 trx_state: RUNNING
       trx_isolation_level: READ COMMITTED
                 trx_query: NULL
     trx_requested_lock_id: NULL
         trx_tables_locked: 1

**Comment by jonesde** [comment] 2017-12-15 00:13
If you can track down where that long lasting lock is coming from I can look into it more and if it is a Moqui issue probably fix it based on that, otherwise I don't see anything that can be done (aside from gather more information).

What happens with this lock for the minute or few minutes after it is created? All transactions should time out, and all locks released when they do, but the transaction timeout for Moqui (in the Bitronix transaction manager) is not the same as the transaction timeout in the database. By default in Moqui the tx timeout is 60 seconds (except for some services that go MUCH longer), but this may not be getting to the database as a limit to set on its timeout and the database timeout is likely much longer so after the app server transaction time out the transaction in the database could remain, especially if the thread freezes in the app server and doesn't clean up (commit or rollback) the DB transaction.

**Comment by jonesde** [comment] 2018-01-17 17:58
Closing as part of general cleanup for the move to HiveMind and for no activity on this issue. If this comes up again feel free to create a request on moqui.org. For more information see:

https://www.moqui.org/m/docs/moqui/Community+Guide

**Closed by jonesde** 2018-01-17 17:58 UTC
