### ISSUE TITLE
issue with transaction cache when do update entity 

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#126] opened 2016-09-30 16:14 UTC
Problem happened when an entityvalue is created in a transaction, then is updated by using EntityAutoService (update#entityName) in which in-map is just contains fields to be updated.

txCache will store an entityvalue with only PKs and fields exists in the in-parameters, others are null. 

This situation is not mentioned in list limitations of transaction cache yet, so I don't know if this is a bug or just the way Moqui does at this moment.

**Comment by jonesde** [comment] 2016-10-01 15:19
What are you actually having an issue with? TransactionCache supports partial values just like the entity-auto CrUD services to avoid forcing a query of a full value just to update it (aside from various cases where the framework does this automatically when the latest data is needed).

Normally this isn't an issue but could be if you write a partial value and then do a query looking for the full value. There is code in a few places to handle this scenario and get the full value, so to make progress on this more information is needed about what your code looks like (which operations you are performing) and where it goes wrong.

In general when reporting a bug:

- what you did (including code, etc so it can be reproduced)
- what happened
- how it was different from what you expected

**Comment by locnguyenx** [comment] 2016-10-02 02:42
**What I did:**
EntityA has fields: entityId, statusId, type (enable audit), totalAmount,...

1. Service 1:
a. Create a record of EntityA which have statusId = 'Draft', type='A'
b. Do some processing and update: totalAmount = somevalue
c. call Service 2 with param: entityId

2. Service 2:
- Lookup EntityA by entityId, expected to get statusId, type to do sth. However, if Transaction Cache in place, all other fields that are not inputted in 1b step are null. 

If I try to add 1 more param statusId = 'Draft' into step 1b, then I get full value in Service 2 and everything is ok. But I think it's curious when update a field that value is not changed

**Comment by locnguyenx** [comment] 2016-10-02 03:15
Do debug in TransactionCache and EntityValueBase update, I find that due to framework checks needsAuditLog,  does refresh dbValueMap, set flag isFromDb = true and skips merging updated fields into ev valueMap
Do I must get dbValueMap and merge myself before using it?

**Comment by jonesde** [comment] 2016-10-04 15:46
This could be handled automatically, I'll look into it. The reason passing in a statusId results in having all fields for the EntityValue is that whenever updating the status the entity-auto services get the full record from the DB in order to check the status transition.

**Comment by jonesde** [comment] 2016-10-07 17:07
I looked into the code related to this a bit more and I see what you mean, there is a hole in the way the TransactionCache, and potentially other code, assumes that if an EntityValue is from the DB then the valueMap will be fully populated but in this scenario that won't be the case.

In commit #ce645a0 I updated the setDbValueMap() method to populate the main valueMap with fields it does not already contain. That should fix the issue you are running into, please test and comment here about how it goes.

**Comment by locnguyenx** [comment] 2016-10-09 08:59
This commit fixes my issue. 
The record got from entityfind with TransactionCache has full value set as expected

**Comment by jonesde** [comment] 2016-10-09 14:58
Great, thank you again, seems resolved so I'll close this.

**Closed by jonesde** 2016-10-09 14:58 UTC
Labels: bug
