### ISSUE TITLE
Unable to build Moqui Framework 2.1.3

### ISSUE THREAD

**Issue by Ndirangug** [moqui/moqui-framework#460] opened 2021-02-15 15:32 UTC
Hello. I'm trying to get started with Moqui. I have followed the tutorial at https://www.moqui.org/m/docs/framework/Run+and+Deploy  .The first few steps work fine but the  ./gradlew load command fails with the following errors:

> Task :load FAILED
Using temporary directory: /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/execwartmp
Error loading jars in war file [file:/media/georgen/LOCAL%20DISK1/George_Ndirangu/Learning/moqui/moqui-framework/moqui.war]: java.io.IOException: Invalid argument
Determined runtime from Java system property: runtime
Canonicalized runtimePath: /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime
Determined conf from Java system property: conf/MoquiDevConf.xml
Starting ElasticSearch install found in runtime/elasticsearch, pid file not found (/usr/lib/jvm/java-11-openjdk-amd64)
Loading data with args {load=, types=all}
java.lang.ClassNotFoundException: Class [org.moqui.Moqui] not found
        at MoquiStart$StartClassLoader.loadClass(MoquiStart.java:767)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at MoquiStart.main(MoquiStart.java:144)
Error loading or running Moqui.loadData with args [{load=, types=all}]: java.lang.ClassNotFoundException: Class [org.moqui.Moqui] not found

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':load'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
27 actionable tasks: 6 executed, 21 up-to-date

I am running Ubuntu 20.04.2 on my laptop with openjdk 11.0.10

**Comment by Ndirangug** [comment] 2021-02-15 15:35
The gradle version im using is gradle-5.6.4

**Comment by jonesde** [comment] 2021-02-15 23:32
There is insufficient information here to comment, specifically steps to reproduce. All we can really see here is that the org.moqui.Moqui class could not be found, likely due to an error during the build that happened long before this.

Which commands did you run before this, preferably all from git clone but at least the last one exactly (was it './gradlew load') and from which directory? Also, what was the full log output following the gradle command instead of just this snippet?

In general please see:

https://moqui.org/m/docs/moqui/Issue+and+Pull+Request+Guide#bugs-and-general-issues

**Comment by jonesde** [comment] 2021-02-15 23:34
Wait, what is 'Moqui 1.2.13'? There has never been a release of Moqui with that version and the closest is 1.2.0 which was released in Dec 2012.

**Comment by Ndirangug** [comment] 2021-02-16 07:15
Sorry. That was a typo. I meant Moqui Framework 2.1.3.

Steps to reproduce are:
1. ` git clone git@github.com:moqui/moqui-framework.git`
```bash
Cloning into 'moqui-framework'...
remote: Enumerating objects: 437, done.
remote: Counting objects: 100% (437/437), done.
remote: Compressing objects: 100% (239/239), done.
remote: Total 30152 (delta 177), reused 323 (delta 91), pack-reused 29715
Receiving objects: 100% (30152/30152), 12.32 MiB | 117.00 KiB/s, done.
Resolving deltas: 100% (15415/15415), done.
```
2. `cd moqui-framework`

3.  `./gradlew getComponent -Pcomponent=PopCommerce`
```bash
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :getComponent
Getting moqui-runtime (type git) from https://github.com/moqui/moqui-runtime.git to runtime
Downloaded moqui-runtime to runtime
Getting PopCommerce (type git) from https://github.com/moqui/PopCommerce.git to runtime/component/PopCommerce
Downloaded PopCommerce to runtime/component/PopCommerce
Getting moqui-fop (type git) from https://github.com/moqui/moqui-fop.git to runtime/component/moqui-fop
Downloaded moqui-fop to runtime/component/moqui-fop
Getting mantle-udm (type git) from https://github.com/moqui/mantle-udm.git to runtime/component/mantle-udm
Downloaded mantle-udm to runtime/component/mantle-udm
Getting mantle-usl (type git) from https://github.com/moqui/mantle-usl.git to runtime/component/mantle-usl
Downloaded mantle-usl to runtime/component/mantle-usl
Getting SimpleScreens (type git) from https://github.com/moqui/SimpleScreens.git to runtime/component/SimpleScreens
Downloaded SimpleScreens to runtime/component/SimpleScreens
Got component PopCommerce, dependent components checked: [PopCommerce, SimpleScreens, mantle-udm, mantle-usl, moqui-fop]

BUILD SUCCESSFUL in 4m 44s
1 actionable task: 1 executed

```

4. ` ./gradlew getComponent -Pcomponent=HiveMind`

```bash

> Task :getComponent
Getting HiveMind (type git) from https://github.com/moqui/HiveMind.git to runtime/component/HiveMind
Downloaded HiveMind to runtime/component/HiveMind
Got component HiveMind, dependent components checked: [HiveMind, SimpleScreens, mantle-udm, mantle-usl, moqui-fop]

BUILD SUCCESSFUL in 44s
1 actionable task: 1 executed

```

5. `./gradlew downloadElasticSearch`

```bash

> Task :downloadElasticSearch
Downloading ElasticSearch from https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.4.2-no-jdk-linux-x86_64.tar.gz

BUILD SUCCESSFUL in 16m 8s
1 actionable task: 1 executed

```

6. `./gradlew load`

```bash

> Task :framework:compileStartJava
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/src/start/java/MoquiStart.java:820: warning: [deprecation] getPackage(String) in ClassLoader has been deprecated
            if (getPackage(packageName) == null) {
                ^
1 warning

> Task :moqui-util:compileJava
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/moqui-util/src/main/java/org/moqui/util/MClassLoader.java:590: warning: [deprecation] getPackage(String) in ClassLoader has been deprecated
        if (getPackage(packageName) == null) {
            ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/moqui-util/src/main/java/org/moqui/util/RestClient.java:705: warning: [deprecation] finalize() in Object has been deprecated
        @Override protected void finalize() throws Throwable {
                                 ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/moqui-util/src/main/java/org/moqui/util/RestClient.java:710: warning: [deprecation] finalize() in Object has been deprecated
            super.finalize();
                 ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/moqui-util/src/main/java/org/moqui/util/RestClient.java:775: warning: [deprecation] finalize() in Object has been deprecated
        @Override protected void finalize() throws Throwable {
                                 ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/moqui-util/src/main/java/org/moqui/util/RestClient.java:780: warning: [deprecation] finalize() in Object has been deprecated
            super.finalize();
                 ^
5 warnings

> Task :framework:compileGroovy
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/context/ExecutionContextFactoryImpl.java:16: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
protected static final boolean isTraceEnabled = new java.lang.Boolean((boolean)false);
                                                ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/context/ExecutionContextFactoryImpl.java:17: warning: [deprecation] Long(long) in Long has been deprecated
public final long initStartTime = new java.lang.Long((long)0);
                                  ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/context/ExecutionContextFactoryImpl.java:78: warning: [deprecation] finalize() in Object has been deprecated
@java.lang.Override() public  void finalize()throws java.lang.Throwable { }
                                   ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/entity/EntityFacadeImpl.java:17: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
protected static final boolean isTraceEnabled = new java.lang.Boolean((boolean)false);
                                                ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/context/TransactionFacadeImpl.java:17: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
protected static final boolean isTraceEnabled = new java.lang.Boolean((boolean)false);
                                                ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/context/TransactionFacadeImpl.java:27: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
protected static final boolean requireNewThread = new java.lang.Boolean((boolean)false);
                                                  ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/entity/EntityDefinition.java:18: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
public final boolean isViewEntity = new java.lang.Boolean((boolean)false);
                                    ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/entity/EntityDefinition.java:19: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
public final boolean isDynamicView = new java.lang.Boolean((boolean)false);
                                     ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/entity/EntityCache.java:17: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
protected final boolean distributedCacheInvalidate = new java.lang.Boolean((boolean)false);
                                                     ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/service/ServiceEcaRule.java:20: warning: [deprecation] Integer(int) in Integer has been deprecated
public final int priority = new java.lang.Integer((int)0);
                            ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/service/ServiceEcaRule.java:21: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
protected final boolean nameIsPattern = new java.lang.Boolean((boolean)false);
                                        ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/service/ServiceEcaRule.java:22: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
protected final boolean runOnError = new java.lang.Boolean((boolean)false);
                                     ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/screen/ScreenRenderImpl.java:16: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
protected static final boolean isTraceEnabled = new java.lang.Boolean((boolean)false);
                                                ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/src/main/groovy/org/moqui/impl/entity/EntityListIteratorImpl.java:379: warning: [deprecation] finalize() in Object has been deprecated
    protected void finalize() throws Throwable {
                   ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/src/main/groovy/org/moqui/impl/entity/EntityListIteratorImpl.java:397: warning: [deprecation] finalize() in Object has been deprecated
        super.finalize();
             ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/src/main/groovy/org/moqui/impl/entity/EntityListIteratorWrapper.java:190: warning: [deprecation] finalize() in Object has been deprecated
    @Override protected void finalize() throws Throwable {
                             ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/src/main/groovy/org/moqui/impl/entity/EntityListIteratorWrapper.java:195: warning: [deprecation] finalize() in Object has been deprecated
        super.finalize();
             ^
/media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/framework/build/tmp/compileGroovy/groovy-java-stubs/org/moqui/impl/entity/EntityDatasourceFactoryImpl.java:17: warning: [deprecation] Long(long) in Long has been deprecated
protected static final long DS_RETRY_SLEEP = new java.lang.Long((long)0);
                                             ^
18 warnings
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/georgen/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.14/f0a005fb21e7bd9b7ebf04cd2ecda0fc8f3be59d/groovy-2.5.14.jar) to method java.util.AbstractCollection.hugeCapacity(int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :runtime:base-component:webroot:downloadFiles
Downloading http://cdnjs.cloudflare.com/ajax/libs/rsvp/4.8.3/rsvp.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/rsvp/rsvp.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/twitter-bootstrap/css/bootstrap.min.css
Downloading http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/twitter-bootstrap/js/bootstrap.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/fonts/glyphicons-halflings-regular.eot to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/twitter-bootstrap/fonts/glyphicons-halflings-regular.eot
Downloading http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/fonts/glyphicons-halflings-regular.svg to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/twitter-bootstrap/fonts/glyphicons-halflings-regular.svg
Downloading http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/fonts/glyphicons-halflings-regular.ttf to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/twitter-bootstrap/fonts/glyphicons-halflings-regular.ttf
Downloading http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/fonts/glyphicons-halflings-regular.woff to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/twitter-bootstrap/fonts/glyphicons-halflings-regular.woff
Downloading http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/fonts/glyphicons-halflings-regular.woff2 to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/twitter-bootstrap/fonts/glyphicons-halflings-regular.woff2
Downloading http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css
Downloading http://cdnjs.cloudflare.com/ajax/libs/mouse0270-bootstrap-notify/3.1.7/bootstrap-notify.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/mouse0270-bootstrap-notify/bootstrap-notify.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/font-awesome/css/font-awesome.min.css
Downloading http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/FontAwesome.otf to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/font-awesome/fonts/FontAwesome.otf
Downloading http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.eot to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/font-awesome/fonts/fontawesome-webfont.eot
Downloading http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.svg to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/font-awesome/fonts/fontawesome-webfont.svg
Downloading http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.ttf to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/font-awesome/fonts/fontawesome-webfont.ttf
Downloading http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/font-awesome/fonts/fontawesome-webfont.woff
Downloading http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2 to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/font-awesome/fonts/fontawesome-webfont.woff2
Downloading http://cdnjs.cloudflare.com/ajax/libs/jeditable.js/1.7.3/jeditable.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jeditable.js/jeditable.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jquery/jquery.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.1/jquery.form.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jquery.form/jquery.form.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.3.4/jquery.inputmask.bundle.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jquery.inputmask/jquery.inputmask.bundle.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jquery-validate/jquery.validate.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jquery-validate/additional-methods.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.8/jstree.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jstree/jstree.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.8/themes/default/style.min.css to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jstree/themes/default/style.min.css
Downloading http://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.8/themes/default/32px.png to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jstree/themes/default/32px.png
Downloading http://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.8/themes/default/40px.png to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jstree/themes/default/40px.png
Downloading http://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.8/themes/default/throbber.gif to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/jstree/themes/default/throbber.gif
Downloading http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/moment.js/moment-with-locales.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/select2/css/select2.min.css
Downloading http://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/select2-bootstrap-theme/select2-bootstrap.min.css
Downloading http://cdnjs.cloudflare.com/ajax/libs/Selectivity.js/2.1.0/selectivity-full.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/Selectivity.js/selectivity-full.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/Selectivity.js/2.1.0/selectivity-full.min.css to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/Selectivity.js/selectivity-full.min.css
Downloading http://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.jquery.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/typeahead.js/typeahead.jquery.min.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/vue/vue.js
Downloading http://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/vue/vue.min.js
Downloading https://cdn.jsdelivr.net/npm/quasar@1.14.7/dist/quasar.min.css to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/quasar/quasar.min.css
Downloading https://cdn.jsdelivr.net/npm/quasar@1.14.7/dist/quasar.umd.min.js to /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime/base-component/webroot/screen/webroot/libs/quasar/quasar.umd.min.js

> Task :load FAILED
Using temporary directory: /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/execwartmp
Error loading jars in war file [file:/media/georgen/LOCAL%20DISK1/George_Ndirangu/Learning/moqui/moqui-framework/moqui.war]: java.io.IOException: Invalid argument
Determined runtime from Java system property: runtime
Canonicalized runtimePath: /media/georgen/LOCAL DISK1/George_Ndirangu/Learning/moqui/moqui-framework/runtime
Determined conf from Java system property: conf/MoquiDevConf.xml
Starting ElasticSearch install found in runtime/elasticsearch, pid file not found (/usr/lib/jvm/java-11-openjdk-amd64)
Loading data with args {load=, types=all}
Error loading or running Moqui.loadData with args [{load=, types=all}]: java.lang.ClassNotFoundException: Class [org.moqui.Moqui] not found
java.lang.ClassNotFoundException: Class [org.moqui.Moqui] not found
        at MoquiStart$StartClassLoader.loadClass(MoquiStart.java:767)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at MoquiStart.main(MoquiStart.java:144)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':load'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 40s
27 actionable tasks: 26 executed, 1 up-to-date

```

**Comment by Ndirangug** [comment] 2021-02-16 07:19
What was expected:
That after following the steps on the tutorial https://www.moqui.org/m/docs/framework/Run+and+Deploy, I would have a working installation of the moqui framework on my laptop.

**Closed** 2021-04-04 18:17 UTC
