### ISSUE TITLE
Connection Closing for a user.

### ISSUE THREAD

**Issue by RollaAshokkumar** [moqui/moqui-framework#203] opened 2017-04-07 06:34 UTC
Ones the user login for that user the connection will be opens. We have given as "pool-maxsize="200"".  For a single user if a transition is completed is there any way to close that connection for that user immediately.

We are facing a problem Like:
Caused by: java.sql.SQLException: unable to get a connection from pool of a PoolingDataSource containing an XAPool of resource DEFAULT_transactional_DS with 3 connection(s) (1 still available)
	at bitronix.tm.resource.jdbc.PoolingDataSource.getConnection(PoolingDataSource.java:331)
	at org.moqui.impl.entity.EntityFacadeImpl.getConnection(EntityFacadeImpl.groovy:1488)
	at org.moqui.impl.entity.EntityQueryBuilder.makeConnection(EntityQueryBuilder.groovy:78)
	at org.moqui.impl.entity.EntityFindImpl.oneExtended(EntityFindImpl.groovy:79)

Caused by: bitronix.tm.internal.BitronixRuntimeException: cannot get valid connection from an XAPool of resource DEFAULT_transactional_DS with 3 connection(s) (1 still available) after trying for 30s
	at bitronix.tm.resource.common.XAPool.getConnectionHandle(XAPool.java:224)
	at bitronix.tm.resource.common.XAPool.getConnectionHandle(XAPool.java:150)
	at bitronix.tm.resource.jdbc.PoolingDataSource.getConnection(PoolingDataSource.java:327)

**Comment by jonesde** [comment] 2017-04-07 07:01
Those error messages match the issue you described. Something else going on and there should be additional log details before and/or after this snippet. If it can't get a connection there is usually an issue connecting to the database or the connection pool is in an invalid state or something (though I've never seen anything like this with Bitronix, even in heavy load tests with intentional errors).

On a more general note all connections are released to the pool when transactions are completed (committed or rolled back). Unless you are doing custom transaction management through the TransactionFacade or the JTA API directly this is done automatically (ie for all services, screens, etc).

More details are needed to do anything about this (ie the issue is not actionable with just what is there so far). The best would be to have steps to reproduce.

**Comment by RollaAshokkumar** [comment] 2017-04-07 08:00
Ok thank you. The problem we are facing, server is working for 5-6 days, after that if we are trying to access the URL it is throwing error. I am attaching log file.  We don't know what it is happening  and we are checking root case for that problem.
[logfile.pdf](https://github.com/moqui/moqui-framework/files/904900/logfile.pdf)

**Comment by jonesde** [comment] 2017-04-07 08:54
This really isn't a forum for debugging your code, but I will say that from less than a minute of scanning through your log you have some serious bugs in your code including NullPointerException and dead locks.

I'm closing this issue as invalid. If you track down an actual framework error that can be reproduced please feel free to open another issue.

**Closed by jonesde** 2017-04-07 08:54 UTC
Labels: invalid
