### ISSUE TITLE
ScheduledJobRunner run error background

### ISSUE THREAD

**Issue by gagaboy** [moqui/moqui-framework#256] opened 2017-09-11 13:50 UTC
I got these error log below frequently in the background on my mac with mysql or postgressql which   seems occur in jobs run : 
`
--- 2017-09-11 21:31:49.930 [pool-2-thread-2] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 Executed query with SQL [SELECT JOB_NAME, JOB_RUN_ID, LAST_RUN_TIME, LAST_UPDATED_STAMP FROM SERVICE_JOB_RUN_LOCK WHERE JOB_NAME = ? FOR UPDATE] and parameters [[jobName:clean_ElasticSearchLogMessages_daily]] in [0] seconds
--- 2017-09-11 21:32:49.923 [pool-2-thread-4] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 Executed query with SQL [SELECT JOB_NAME, JOB_RUN_ID, LAST_RUN_TIME, LAST_UPDATED_STAMP FROM SERVICE_JOB_RUN_LOCK WHERE JOB_NAME = ? FOR UPDATE] and parameters [[jobName:clean_ArtifactData_daily]] in [0] seconds
--- 2017-09-11 21:32:49.925 [pool-2-thread-4] WARN                  bitronix.tm.resource.common.XAPool []
 error closing a JdbcPooledConnection from datasource transactional_DS in state CLOSED with usage count 0 wrapping org.postgresql.xa.PGXAConnection@11b36fde
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_152-ea]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752) ~[?:1.8.0_152-ea]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750) ~[?:1.8.0_152-ea]
	at bitronix.tm.resource.jdbc.LruStatementCache.clear(LruStatementCache.java:171) ~[btm-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at bitronix.tm.resource.jdbc.JdbcPooledConnection.close(JdbcPooledConnection.java:150) ~[btm-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at bitronix.tm.resource.common.XAPool.expireStatefulHolder(XAPool.java:534) [btm-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at bitronix.tm.resource.common.XAPool.getInPool(XAPool.java:320) [btm-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at bitronix.tm.resource.common.XAPool.getConnectionHandle(XAPool.java:181) [btm-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at bitronix.tm.resource.common.XAPool.getConnectionHandle(XAPool.java:150) [btm-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at bitronix.tm.resource.jdbc.PoolingDataSource.getConnection(PoolingDataSource.java:277) [btm-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.moqui.impl.entity.EntityFacadeImpl.getConnection(EntityFacadeImpl.groovy:1900) [moqui-framework-2.1.0-rc3.jar:2.1.0-rc3]
	at org.moqui.impl.entity.EntityQueryBuilder.makeConnection(EntityQueryBuilder.java:56) [moqui-framework-2.1.0-rc3.jar:2.1.0-rc3]
	at org.moqui.impl.entity.EntityFindImpl.oneExtended(EntityFindImpl.java:74) [moqui-framework-2.1.0-rc3.jar:2.1.0-rc3]
	at org.moqui.impl.entity.EntityFindBase.oneInternal(EntityFindBase.groovy:875) [moqui-framework-2.1.0-rc3.jar:2.1.0-rc3]
	at org.moqui.impl.entity.EntityFindBase.one(EntityFindBase.groovy:678) [moqui-framework-2.1.0-rc3.jar:2.1.0-rc3]
	at org.moqui.impl.service.ScheduledJobRunner.run(ScheduledJobRunner.groovy:111) [moqui-framework-2.1.0-rc3.jar:2.1.0-rc3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152-ea]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_152-ea]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_152-ea]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_152-ea]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_152-ea]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_152-ea]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152-ea]
--- 2017-09-11 21:32:49.928 [pool-2-thread-4] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 Executed query with SQL [SELECT JOB_NAME, JOB_RUN_ID, LAST_RUN_TIME, LAST_UPDATED_STAMP FROM SERVICE_JOB_RUN_LOCK WHERE JOB_NAME = ? FOR UPDATE] and parameters [[jobName:clean_ServiceJobRun_daily]] in [0] seconds
--- 2017-09-11 21:32:49.930 [pool-2-thread-4] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 Executed query with SQL [SELECT JOB_NAME, JOB_RUN_ID, LAST_RUN_TIME, LAST_UPDATED_STAMP FROM SERVICE_JOB_RUN_LOCK WHERE JOB_NAME = ? FOR UPDATE] and parameters [[jobName:recalculate_GlAccountOrgSummaries]] in [0] seconds
--- 2017-09-11 21:32:49.932 [pool-2-thread-4] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 Executed query with SQL [SELECT JOB_NAME, JOB_RUN_ID, LAST_RUN_TIME, LAST_UPDATED_STAMP FROM SERVICE_JOB_RUN_LOCK WHERE JOB_NAME = ? FOR UPDATE] and parameters [[jobName:clean_ElasticSearchLogMessages_daily]] in [0] seconds
--- 2017-09-11 21:33:49.921 [pool-2-thread-1] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 Executed query with SQL [SELECT JOB_NAME, JOB_RUN_ID, LAST_RUN_TIME, LAST_UPDATED_STAMP FROM SERVICE_JOB_RUN_LOCK WHERE JOB_NAME = ? FOR UPDATE] and parameters [[jobName:clean_ArtifactData_daily]] in [0] seconds
--- 2
`

**Comment by gagaboy** [comment] 2017-09-11 13:53
These errors are irregularly and happen frequently

**Comment by gagaboy** [comment] 2017-09-12 03:55
Well,I just launch moqui and do nothing, then a few minutes later ,the errors occur.
And the lastest version of moqui seems remove Atomikos support？

**Comment by jonesde** [comment] 2017-09-12 04:54
Atomikos support is in the moqui/moqui-atomikos component.

The error you included is a symptom, not the cause. You need to find the cause. It could be in a scheduled job or something related to the database. There are a few production systems I have access to and/or maintain, including one very active one I monitor regularly, and haven't seen any errors like this. 

I've seen errors like this before, but usually in development or if there is something buggy throwing a bunch of errors.

**Comment by jonesde** [comment] 2017-10-13 04:36
Any updates on this? If not, and if I can't reproduce the issue, I'll close it.

**Closed** 2017-10-18 05:44 UTC
Labels: invalid

**Comment by gagaboy** [comment] 2018-04-21 14:08
Thanks for Will's help. The reason is I add a maven repo “https://oss.sonatype.org/content/groups/public” , and gradle auto download the org.codehaus.btm:btm:3.0.0-SNAPSHOT jar which from jboss 3rd jar, and not from the framework libs
