### ISSUE TITLE
Can not delete localization record

### ISSUE THREAD

**Issue by corncore** [moqui/moqui-framework#36] opened 2016-03-08 09:08 UTC
Can not delete localization record on path:apps/system/Localization

**Comment by jonesde** [comment] 2016-03-08 23:23
I could not reproduce this, the delete button works fine on both screens under the Localization screen, i.e. "/apps/system/Localization/Messages" and "/apps/system/Localization/EntityFields".

What was the error in your log file? Which version of Moqui are you using?

**Comment by corncore** [comment] 2016-03-09 09:41
version: moqui-1.6.1
path: "/apps/system/Localization/Messages"

click "delete" button,but run updateLocalizedMessage
log
-- 2016-03-09 17:34:25.252 [ndlerThread[19]] INFO    org.moqui.impl.screen.ScreenRenderImpl []
 Finished transition [[apps, system, Localization, Messages, updateLocalizedMessage]] in [0.005] seconds , redirecting to [http://localhost:8080/apps/system/Localization/Messages]
--- 2016-03-09 17:34:25.958 [ndlerThread[19]] INFO        org.moqui.impl.webapp.MoquiServlet []
 Finished request to [/apps/system/Localization/Messages] of content type [text/html;charset=UTF-8] in [0.699] seconds in session [1446211202a0bb03121c653929b7769d] thread [130:RequestHandlerThread[19]]

**Comment by corncore** [comment] 2016-03-09 10:01
the same issues on https://demo.moqui.org/apps/system/Localization/Messages

**Comment by jonesde** [comment] 2016-03-09 16:12
I don't see this behavior, even on demo.moqui.org. I click on the delete button and the records disappear as expected (calling the deleteLocalizedMessage transition).

Perhaps there is different behavior because you are using a different browser... which browser are you using and which version?

When you say you are clicking on the "delete" button do you mean the button that says "Delete" or the checkbox to the left of it in the "Update" column?

**Comment by jonesde** [comment] 2016-03-16 18:25
Any updates on this? If not I'll close the issue.

**Closed** 2016-03-22 15:10 UTC
Labels: bug, invalid
