### ISSUE TITLE
Error when connecting to MS SQL Server 

### ISSUE THREAD

**Issue by amirRezaHamzehi** [moqui/moqui-framework#314] opened 2018-04-17 14:36 UTC
I am trying to use Moqui with MS SQL Server , but I'm having this problem : 

```
19:03:26.713  WARN         main         o.moqui.i.e.EntityQueryBuilder Error in JDBC update for SQL INSERT INTO ARTIFACT_HIT_BIN (HIT_BIN_ID, ARTIFACT_TYPE, ARTIFACT_SUB_TYPE, ARTIFACT_NAME, SE
RVER_IP_ADDRESS, SERVER_HOST_NAME, BIN_START_DATE_TIME, BIN_END_DATE_TIME, HIT_COUNT, TOTAL_TIME_MILLIS, TOTAL_SQUARED_TIME, MIN_TIME_MILLIS, MAX_TIME_MILLIS, SLOW_HIT_COUNT, LAST_UPDATED_STAMP
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
19:03:26.714  WARN         main                o.m.i.e.EntityValueImpl Error creating [moqui.server.ArtifactHitBin: {hitBinId=100001, lastUpdatedStamp=2018-04-17 07:33:26.712, artifactType=AT_E
NTITY, hitCount=24, artifactSubType=refresh, binStartDateTime=2018-04-17 07:33:25.823, minTimeMillis=0.236771000000000009233502851202501915395259857177734375, serverHostName=amirreza-hamzeh, bi
nEndDateTime=2018-04-17 07:33:26.706, totalSquaredTime=9.75741110191599858580957516096532344818115234375, slowHitCount=0, artifactName=moqui.basic.EnumerationType, totalTimeMillis=13.6257039999
999971513489072094671428203582763671875, serverIpAddress=192.168.0.101, maxTimeMillis=3.532021999999999994912514011957682669162750244140625}] tx [could not get] con a ConnectionJavaProxy of a J
dbcPooledConnection from datasource transactional_DS in state ACCESSIBLE with usage count 1 wrapping a JDBC LrcXAConnection on a JDBC LrcConnectionJavaProxy on ConnectionID:1 ClientConnectionId
: fc2d615f-f501-4ee8-bc95-712411ef6dda on a JDBC LrcConnectionJavaProxy on ConnectionID:1 ClientConnectionId: fc2d615f-f501-4ee8-bc95-712411ef6dda: com.microsoft.sqlserver.jdbc.SQLServerExcepti
on: Error converting data type nvarchar to decimal.
Error loading or running Moqui.loadData with args [{load=}]: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at MoquiStart.main(MoquiStart.java:141)
Caused by: Error creating ArtifactHitBin {hitBinId=100001} [S0001]
        at org.moqui.impl.entity.EntityValueBase.create(EntityValueBase.java:1298)
        at org.moqui.impl.context.ExecutionContextFactoryImpl.destroy(ExecutionContextFactoryImpl.groovy:692)
        at org.moqui.Moqui.loadData(Moqui.java:154)
        ... 5 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Error converting data type nvarchar to decimal.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:548)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:479)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:426)
        at bitronix.tm.resource.jdbc.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
        at org.moqui.impl.entity.EntityQueryBuilder.executeUpdate(EntityQueryBuilder.java:112)
        at org.moqui.impl.entity.EntityValueImpl.createExtended(EntityValueImpl.java:101)
        at org.moqui.impl.entity.EntityValueBase.basicCreate(EntityValueBase.java:1322)
        at org.moqui.impl.entity.EntityValueBase.create(EntityValueBase.java:1288)
        ... 7 more

BUILD SUCCESSFUL
```
[moqui.log](https://github.com/moqui/moqui-framework/files/1920261/moqui.log)

**Thanks for any help .**

**Comment by jonesde** [comment] 2018-04-17 14:59
Steps to reproduce? Please review:

https://www.moqui.org/m/docs/moqui/Issue+and+Pull+Request+Guide

**Comment by jonesde** [comment] 2018-04-21 20:53
FWIW the real error here is: "com.microsoft.sqlserver.jdbc.SQLServerException: Error converting data type nvarchar to decimal"

It looks like a data type issue with the JDBC driver, and I see a method called "SQLServerStatement.getNextResult" in the stack trace so it may be in the results coming back but that doesn't make sense so is more likely in the values passed to the JDBC driver. Do you see any other errors like this as you try to run things?

Usually to fix database or JDBC driver specific errors it is necessary to test using the specific database and JDBC driver. I'm not going to do this, I don't have infrastructure to test against MS SQL Server. For any hope of anyone doing it at least specify the database version used, the JDBC driver and version, and configuration changes used to connect to the database (the MoquiActualConf.xml file you sent a link to on LinkedIn would help with the last part, should link to it or attach it here, not on LinkedIn where no one would know about it from the context of this issue).

**Comment by jonesde** [comment] 2018-04-21 23:14
Just saw the request filed on moqui.org so closing this. Request is available here:

https://www.moqui.org/vapps/hm/Request/EditRequest?requestId=100307

**Closed by jonesde** 2018-04-21 23:14 UTC
