### ISSUE TITLE
Number validation for German number

### ISSUE THREAD

**Issue by mckhoi** [moqui/moqui-framework#302] opened 2018-01-12 18:36 UTC
1.9876 is on German 1,976 -  a comma instead of a point.
I set the system on German and try to insert a number on the example component for "Example Size" that number, but the system gives a error "Please enter a valid number."

**Comment by jonesde** [comment] 2018-01-12 21:45
Going forward please file requests for support on the new HiveMind instance on moqui.org. For more information about community infrastructure see:

https://www.moqui.org/docs/moqui/Community+Guide

In the near future issues on GitHub will be disabled altogether.

This issue is a duplicate of issue #49 on moqui-framework, and related to pull request #93 on moqui-runtime:

https://github.com/moqui/moqui-framework/issues/49
https://github.com/moqui/moqui-runtime/pull/93

**Closed by jonesde** 2018-01-12 21:45 UTC
