### ISSUE TITLE
Error running poll#EmailServer - NoSuchFieldError: SIZE

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-framework#165] opened 2016-12-18 17:54 UTC
While running on local, no problems. After deploying to server, this error occurred:
![emailerror](https://cloud.githubusercontent.com/assets/14863763/21295335/32eed3f0-c553-11e6-8257-875adfd18bfb.PNG)

After surfing the web, there seems to be a possible solution. http://stackoverflow.com/questions/40938389/nosuchfielderror-size-when-fetching-email-through-imap

Can provide more info if necessary.

**Comment by mrovnanik** [comment] 2016-12-18 21:15
When local, I run the app with MoquiDevConf.xml. On server with MoquiProductionConf.xml. Which is obvious, but it's worth mentioning.

**Comment by mrovnanik** [comment] 2016-12-19 09:07
It looks like the Jetty is using javax.mail.glassfish-1.4.1.v201005082020.jar. This may be the problem. I shall override jetty's configuration. Probably.

**Comment by mrovnanik** [comment] 2016-12-19 10:06
I solved the issue by placing javax.mail.1.5.6.jar to /lib/ext of the Jetty. It is probably only a workaround and needs a more robust solution. But at least there is a hint on how to solve such issue, should anyone face it in the future.

![jetty_javax_mail](https://cloud.githubusercontent.com/assets/14863763/21308606/fe3a638a-c5da-11e6-9c69-31f2e9a5cab0.png)

**Comment by jonesde** [comment] 2016-12-19 16:52
So it looks like the issue is that Jetty has an older version of javax.mail that was getting picked up. I don't think there is anything that can be, or needs to be, done in moqui-framework. This is a deployment issue with a classpath conflict (BTW generally best to remove the other jar to make sure it doesn't get picked up) so I'll close the issue. Thank you for documenting it for others who run into it.

**Closed by jonesde** 2016-12-19 16:52 UTC
