### ISSUE TITLE
Pressing the "Clear All Artifact" button on the Cache List screen causes an exception

### ISSUE THREAD

**Issue by aabiabdallah** [moqui/moqui-framework#88] opened 2016-08-16 08:49 UTC
Screen: System >Cache
Exception:
keyType and/or valueType can't be null
at javax.cache.configuration.MutableConfiguration.setTypes(MutableConfiguration.java:194)
at org.moqui.impl.context.CacheFacadeImpl.initCache(CacheFacadeImpl.groovy:251)
at org.moqui.impl.context.CacheFacadeImpl.getCacheInternal(CacheFacadeImpl.groovy:138)
at org.moqui.impl.context.CacheFacadeImpl.getCache(CacheFacadeImpl.groovy:115)
at org.moqui.context.CacheFacade$getCache.call(Unknown Source)
at CacheList_xml_transition_clearArtifactCaches_actions$_run_closure1.doCall(CacheList_xml_transition_clearArtifactCaches_actions:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
at groovy.lang.Closure.call(Closure.java:414)
at groovy.lang.Closure.call(Closure.java:430)
at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at CacheList_xml_transition_clearArtifactCaches_actions.run(CacheList_xml_transition_clearArtifactCaches_actions:6)
at org.moqui.impl.actions.XmlAction.run(XmlAction.groovy:66)
at org.moqui.impl.screen.ScreenDefinition$TransitionItem.run(ScreenDefinition.groovy:702)
at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:239)
at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:233)
at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:233)
at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:233)
at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:233)
at org.moqui.impl.screen.ScreenRenderImpl.internalRender(ScreenRenderImpl.groovy:349)
at org.moqui.impl.screen.ScreenRenderImpl.render(ScreenRenderImpl.groovy:176)
at org.moqui.impl.webapp.MoquiServlet.doScreenRequest(MoquiServlet.groovy:79)
at org.moqui.impl.webapp.MoquiServlet.service(MoquiServlet.groovy:54)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:397)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
at org.eclipse.jetty.server.Server.handle(Server.java:524)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
at java.lang.Thread.run(Thread.java:745)

**Comment by jonesde** [comment] 2016-08-16 20:31
In the latest code I'm unable to reproduce this, both the Clear All and Clear All Artifact buttons work fine.

Which version of moqui are you using (how did you download/etc)?

Do you have any configuration changes? It's possible you have an invalid cache configuration or something...

**Comment by aabiabdallah** [comment] 2016-08-16 20:41
I have the latest code from commit #daef5f9. I haven't done any changes to the Moqui configuration except for adding a <after-startup> action in the webapp-list section. I'm running JDK 1.8.0_31. Could it be related to a component? I do have a new component under runtime/component that I'm working on.

**Comment by jonesde** [comment] 2016-08-16 20:49
When you updated moqui-framework did you also update moqui-runtime? Generally it's best to update using 'gradle gitPullAll' which uses a git client running in gradle and because it knows about the runtime directory and all the components it can pull all of them. If there are errors on any it is better to go back to plain git on the command line or a git desktop app to see what went wrong (merge conflicts, etc).

Also make sure to build after updating, if you are running with 'gradle run' it will do this (the run task depends on build).

**Comment by aabiabdallah** [comment] 2016-08-16 20:56
I cleared the runtime when I updated the code and allowed grade to download the new runtime from GitHub.

Digging a bit into the code, I found that the exception is being thrown for cache with name "kie.component.releaseId". This cache doesn't seem to exist on my machine. If I remove this from the clearArtifactCaches transaction action it works perfectly. Any ideas what this particular cache isn't present?

**Comment by jonesde** [comment] 2016-08-16 20:59
Ah, that's useful. That cache will only exist if the moqui-kie component is in place. I'll tweak the code to just clear the caches in the list that exist.

**Comment by jonesde** [comment] 2016-08-16 21:09
This is fixed in moqui-runtime commit #9f3c89d (was an issue in moqui-runtime, not in moqui-framework; all web ui artifacts including the tool component are in moqui-runtime).

Would you update moqui-runtime and see if this works for you? If so this issue can be closed.

**Comment by aabiabdallah** [comment] 2016-08-16 21:40
Thanks David, I can confirm that this is working properly now.

**Closed** 2016-08-16 22:40 UTC
