### ISSUE TITLE
Locking related issue using Postgresql

### ISSUE THREAD

**Issue by jenshp** [moqui/moqui-framework#219] opened 2017-06-08 03:39 UTC
I have seen an issue a couple of times on a production server, where (normally after having updated entity changes using the datasource.@startup-add-missing="true" configuration) a kind of a deadlock occurs on the moqui.security.UserLoginHistory entity when logging in successfully. The result is that the webroot screen does not get rendered, and the request fails when the Bitronix Transaction times out after a minute.

It is not a real deadlock, but one new transaction performing a creation is being blocked by the "current" transaction after performing a find on the same entity (UserLoginHistory). In postgres, the latter is in "idle in transaction" state.

I have been able to avoid this problem by changing the creation of the entity record in an asynchronous call rather than a synchronous one (see attached patch [async.txt](https://github.com/moqui/moqui-framework/files/1059875/async.txt)
), but I am not sure that is the right solution.

This problem is not easily reproducible (it does not happen when I re-create the same database via pg_dump/pg_restore and using the same code base on another machine), but has happened a few times now. And once it happens on this machine, it begins to fail consistently on every login attempt for all tested users. Restarting tomcat and postgresql also does not work, but on some occasions rebooting the server made "things work" for a couple of minutes, but afterwards the locking issue re-emerges. Erasing cookies does not seem to avoid it either.

**Comment by jonesde** [comment] 2017-06-08 05:09
Did that patch actually work, ie the UserLoginHistory records are actually getting created and you're not getting errors in the log? I ask because the disableAuthz() call only has an effect on the current thread (the current ExecutionContext) so I would expect a authz error.

Is there anything else in the moqui.log file (or console log) before this? Any warning or other non-stopping error messages? What is at the top of the transaction timeout stack trace (ie is it MoquiShiroRealm:168)?

The strange part is this happening consistently once it happens once. The find one on UserLoginHistory just before the create shouldn't result in any sort of lock, so makes me wonder what other transactions are active that the create/insert operation is waiting on or what else is going on the database, perhaps some sort of transaction isolation or other transaction management setting in the database.

I've been testing quite a bit with Postgres recently as a client is using it and haven't run into issues. Still, this code could be improved to run similar to the ArtifactHit persistence code (or what it used to be like before the current queue and persist approach). I'll make some changes and at least make sure it is working running in the worker thread pool, which will at least keep it from causing problems with login.

**Comment by jonesde** [comment] 2017-06-08 05:22
The change for this is in commit #19694c52. It uses a lower-level method in the framework to run in a worker pool thread.

**Comment by jonesde** [comment] 2017-06-08 05:22
BTW, closing this issue now as you mentioned async persistence would resolve it, and it seems to be one that isn't easy to reproduce. If you see it again after applying this change please do reopen this issue.

**Closed by jonesde** 2017-06-08 05:22 UTC

**Comment by jenshp** [comment] 2017-06-08 13:35
Just to complete the information, yes, the patch included in my post works, the record gets created and no error messages appear in the log. As for the location of the error, the symptoms are that the browser keeps waiting and there is nothing about it in the logs, it just "gets stuck" for a minute and then fails without any output to the browser. Checking the logs, after the transaction timeout you see only that fact and no possible cause (see [locking_log.txt](https://github.com/moqui/moqui-framework/files/1061106/locking_log.txt)).
This happened with PostgreSQL 9.2.18, using the default (read commited) transaction isolation level. While it happened, the only active operations were both, the select (in "idle in transaction" state and the insert (waiting for the lock held by the select) on the UserLoginHistory table.
I will update now and come back if it happens again, thanks!
