### ISSUE TITLE
Search box in dropdown not working (textbox not editable)

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-framework#80] opened 2016-07-19 22:01 UTC
The search box that appears in dropdown is not usable, you cannot write to it. Right now I cloned framework from moqui/moqui-frameworked, used gradle to fetch PopCommerce and compiled it. I was not able get into it, my CSS, JavaScript knowledge is insufficient.

On the first screenshot, that is my local version. The second screen is from the official site's PopCommerce app.

![image](https://cloud.githubusercontent.com/assets/14863763/16967964/3ce11a1c-4e0c-11e6-8475-977922d10bef.png)

![image](https://cloud.githubusercontent.com/assets/14863763/16968060/cd82fc02-4e0c-11e6-82af-f7a02c4f6cee.png)

**Comment by jonesde** [comment] 2016-07-19 22:54
It looks like this is an issue for select2 drop-downs in a modal, outside modal windows it works fine. Looking into the cause...

BTW, I noticed there is a new version of Select2 (4.0.3) and I put that in but it doesn't resolve this issue.

**Comment by mrovnanik** [comment] 2016-07-19 22:56
OK, thanks. I hope I can get deeper into the frontend topics in the future.

**Comment by jonesde** [comment] 2016-07-19 23:21
BTW, this (like most UI issues related to JS/etc) is an issue in moqui-runtime and not moqui-framework. All JS files, templates, etc are in moqui-runtime.

It would take quite a knowledge of JavaScript and specifically Bootstrap and Select2 to fix this, fortunately there are others using these things and Google is around to help find stuff. In moqui-runtime commit #12ef748 there is a fix for this (added a little JS line in Header.html.ftl) and some updates on the Select2 files (which didn't fix this).

**Closed by jonesde** 2016-07-19 23:21 UTC
