### ISSUE TITLE
cannot login - deploy moqui 1.6.3 and runtime in apache-tomcat-8.0.12 in a non-ROOT folder

### ISSUE THREAD

**Issue by zhurichard** [moqui/moqui-framework#50] opened 2016-05-03 03:41 UTC
I'm trying to deploy moqui 1.6.3 and runtime in apache-tomcat-8.0.12 in a non-ROOT folder.

I have done below modification in build.gradle:

> task deployTomcatRuntime << { delete file(tomcatHome + '/runtime'); delete file(tomcatHome + '/webapps/**myweb**'); delete file(tomcatHome + '/webapps/**myweb.war**') copy { from file(plusRuntimeName); into file(tomcatHome + '/webapps'); rename(plusRuntimeName, '**myweb.war**') } }

After commands: gradle cleanAll, gradle buid, gradle addRuntimeTomcat, myweb.war is deployed in tomcat webapp folder successfully.

After that, I use "http://localhost:8080/myweb" to open the root page, and the login page comes "http://localhost:8080/myweb/Login".

And then I give the username and password and click login, but I'm still in login page without any error.

If I change myweb.war to ROOT.war, it will work fine to log into the system.

I put some logs in ScreenRenderImpl and find that the reason is userId lost, but I cannot find out how it is.

> logger.debug("=======internalRender-userId-1.5:" + ec.getUser().getUserId())
>         // check webapp settings for each screen in the path
>         for (ScreenDefinition checkSd in screenUrlInfo.screenRenderDefList) {
> 			logger.debug("=======internalRender-ScreenDefinition:" + checkSd.location)
>             if (!checkWebappSettings(checkSd)) return
>         }

> --- 2016-05-03 10:31:55.275 [nio-8080-exec-1] DEBUG   org.moqui.impl.screen.ScreenRenderImpl []
>  =======**internalRender-userId-1.5:null**
> --- 2016-05-03 10:31:55.275 [nio-8080-exec-1] DEBUG   org.moqui.impl.screen.ScreenRenderImpl []
>  =======internalRender-ScreenDefinition:component://webroot/screen/webroot.xml
> --- 2016-05-03 10:31:55.275 [nio-8080-exec-1] DEBUG   org.moqui.impl.screen.ScreenRenderImpl []
>  =======internalRender-ScreenDefinition:component://webroot/screen/webroot/apps.xml
> --- 2016-05-03 10:31:55.275 [nio-8080-exec-1] DEBUG   org.moqui.impl.screen.ScreenRenderImpl []
>  =======internalRender-ScreenDefinition:component://webroot/screen/webroot/apps/AppList.xml
> --- 2016-05-03 10:31:55.276 [nio-8080-exec-1] INFO    org.moqui.impl.screen.ScreenRenderImpl []
>  Screen at location [component://webroot/screen/webroot/apps/AppList.xml], which is part of [[apps, AppList]] under screen [component://webroot/screen/webroot.xml] **requires authentication but no user is currently logged in.**

**Comment by zhurichard** [comment] 2016-05-03 07:37
I deployed fresh moqui and runtime 1.6.2 for the same testing, I got below issues. I'm sure john.doe has been loaded into database and it is working fine when I deploy the same in ROOT.
It looks like entity-find cannot work in non-ROOT folder. 

> --- 2016-05-03 15:18:39.729 [io-8080-exec-10] WARN  moqui.impl.context.TransactionFacadeImpl []
>  Transaction rollback for [No account found for username john.doe in tenant DEFAULT.
> ]. Here is the current location: 
> org.moqui.BaseException: Rollback location
> 	at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:409) [TransactionFacadeImpl.class:1.6.2]
> 	at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:392) [TransactionFacadeImpl.class:1.6.2]
> 	at org.moqui.impl.screen.ScreenRenderImpl.internalRender(ScreenRenderImpl.groovy:344) [ScreenRenderImpl.class:1.6.2]
> 	at org.moqui.impl.screen.ScreenRenderImpl.render(ScreenRenderImpl.groovy:167) [ScreenRenderImpl.class:1.6.2]
> 	at org.moqui.impl.webapp.MoquiServlet.doScreenRequest(MoquiServlet.groovy:73) [MoquiServlet.class:1.6.2]
> 	at org.moqui.impl.webapp.MoquiServlet.doPost(MoquiServlet.groovy:39) [MoquiServlet.class:1.6.2]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.12]
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.12]
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.12]
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.12]
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.12]
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.12]
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.12]
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) [catalina.jar:8.0.12]
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.12]
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.12]
> 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.12]
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.12]
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:534) [catalina.jar:8.0.12]
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081) [tomcat-coyote.jar:8.0.12]
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) [tomcat-coyote.jar:8.0.12]
> 	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222) [tomcat-coyote.jar:8.0.12]
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566) [tomcat-coyote.jar:8.0.12]
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523) [tomcat-coyote.jar:8.0.12]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_20]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_20]
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.12]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]
> --- 2016-05-03 15:18:39.735 [io-8080-exec-10] INFO    org.moqui.impl.screen.ScreenRenderImpl []
>  Finished transition [Login, login] in 0.035 seconds, redirecting to screen path URL: http://localhost:8080/myweb/Login
> --- 2016-05-03 15:18:39.873 [nio-8080-exec-9] INFO        org.moqui.impl.webapp.MoquiServlet []
>  Finished request to /Login of content type text/html;charset=UTF-8 in 0.135 seconds in session BCBBAA149EF671A8B9A7435299400B35 thread 1447:http-nio-8080-exec-9
>

**Comment by zhurichard** [comment] 2016-05-03 10:37
I try the same in moqui version 1.6.2, it is no issue. Maybe you can ignore this.

**Comment by jonesde** [comment] 2016-05-09 08:09
I tried this with the latest code and could not reproduce it, and from your last comment maybe you found the issue (perhaps a data loading issue?). Closing.

**Closed by jonesde** 2016-05-09 08:09 UTC

**Comment by zhurichard** [comment] 2016-05-09 08:25
I cannot find out the reason. Maybe the data problem. Please closed it. Thanks a lot!
