### ISSUE TITLE
Gradle Load is not Working

### ISSUE THREAD

**Issue by surendar** [moqui/moqui-framework#180] opened 2017-01-30 07:06 UTC
After gradle load all tables are not loading in DB.
For each gradle load it is creating few tables only.
I tried gradle clean every time but nothing is working.
I have checked seed data also.  All are seeding correct data only.

Exception checking for missing columns in table STATUS_FLOW
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 10 ms ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_92]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_92]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2873) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2763) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3299) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1837) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1961) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2537) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2466) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1383) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2460) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:50) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.DatabaseMetaData.getColumns(DatabaseMetaData.java:2334) ~[com.mysql.jdbc_5.1.5.jar:?]
	at org.moqui.impl.entity.EntityDbMeta.getMissingColumns(EntityDbMeta.groovy:279) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDbMeta.internalCheckTable(EntityDbMeta.groovy:119) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDbMeta.checkTableRuntime(EntityDbMeta.groovy:75) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityValueImpl.updateExtended(EntityValueImpl.java:149) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityValueBase.update(EntityValueBase.java:1329) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityValueBase.createOrUpdate(EntityValueBase.java:557) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.service.runner.EntityAutoServiceRunner.storeRecursive(EntityAutoServiceRunner.groovy:396) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.service.runner.EntityAutoServiceRunner.storeEntity(EntityAutoServiceRunner.groovy:352) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$LoadValueHandler.handlePlainMap(EntityDataLoaderImpl.groovy:415) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$EntityXmlHandler.endElement(EntityDataLoaderImpl.groovy:676) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195) [?:1.8.0_92]
	at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:298) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.doCall(EntityDataLoaderImpl.groovy:273) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.call(EntityDataLoaderImpl.groovy) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.doCall(TransactionFacadeImpl.groovy:196) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.call(TransactionFacadeImpl.groovy) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at groovy.lang.Closure.run(Closure.java:495) [moqui_temp2782208534658787434WEB-INF_lib_groovy-2.4.7.jar.:2.4.7]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_92]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_92]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[?:1.8.0_92]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_92]
	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:113) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:160) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:188) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2329) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2774) ~[com.mysql.jdbc_5.1.5.jar:?]
	... 39 more
--- 2017-01-30 12:18:01.506 [   RequireNewTx] WARN        org.moqui.impl.context.TransactionFacadeImpl []
 Transaction rollback. The rollback was originally caused by: Error loading entity data
org.xml.sax.SAXException: Error storing entity [moqui.basic.StatusFlow] value (line 238): org.moqui.entity.EntityException: Error in update of [moqui.basic.StatusFlow: {lastUpdatedStamp=2017-01-30 12:18:01.346, statusFlowId=Default, description=Default status flow across entire system.}] tx a Bitronix Transaction with GTRID [3137322E31372E312E31303500000159EE215E4200000001], status=ACTIVE, 1 resource(s) enlisted (started Mon Jan 30 12:18:01 IST 2017) con Group: transactional, Con: a ConnectionJavaProxy of a JdbcPooledConnection from datasource transactional_DS in state ACCESSIBLE with usage count 1 wrapping a JDBC LrcXAConnection on a JDBC LrcConnectionJavaProxy on com.mysql.jdbc.JDBC4Connection@64f537a9 on a JDBC LrcConnectionJavaProxy on com.mysql.jdbc.JDBC4Connection@64f537a9
	at org.moqui.impl.entity.EntityDataLoaderImpl$EntityXmlHandler.endElement(EntityDataLoaderImpl.groovy:681) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195) ~[?:1.8.0_92]
	at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:298) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.doCall(EntityDataLoaderImpl.groovy:273) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.call(EntityDataLoaderImpl.groovy) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.doCall(TransactionFacadeImpl.groovy:196) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.call(TransactionFacadeImpl.groovy) [moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at groovy.lang.Closure.run(Closure.java:495) [moqui_temp2782208534658787434WEB-INF_lib_groovy-2.4.7.jar.:2.4.7]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: org.moqui.entity.EntityException: Error in update of [moqui.basic.StatusFlow: {lastUpdatedStamp=2017-01-30 12:18:01.346, statusFlowId=Default, description=Default status flow across entire system.}] tx a Bitronix Transaction with GTRID [3137322E31372E312E31303500000159EE215E4200000001], status=ACTIVE, 1 resource(s) enlisted (started Mon Jan 30 12:18:01 IST 2017) con Group: transactional, Con: a ConnectionJavaProxy of a JdbcPooledConnection from datasource transactional_DS in state ACCESSIBLE with usage count 1 wrapping a JDBC LrcXAConnection on a JDBC LrcConnectionJavaProxy on com.mysql.jdbc.JDBC4Connection@64f537a9 on a JDBC LrcConnectionJavaProxy on com.mysql.jdbc.JDBC4Connection@64f537a9
	at org.moqui.impl.entity.EntityValueImpl.updateExtended(EntityValueImpl.java:165) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityValueBase.update(EntityValueBase.java:1329) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityValueBase.createOrUpdate(EntityValueBase.java:557) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.service.runner.EntityAutoServiceRunner.storeRecursive(EntityAutoServiceRunner.groovy:396) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.service.runner.EntityAutoServiceRunner.storeEntity(EntityAutoServiceRunner.groovy:352) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$LoadValueHandler.handlePlainMap(EntityDataLoaderImpl.groovy:415) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$EntityXmlHandler.endElement(EntityDataLoaderImpl.groovy:676) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195) ~[?:1.8.0_92]
	at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:298) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.doCall(EntityDataLoaderImpl.groovy:273) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.doCall(TransactionFacadeImpl.groovy:196) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	... 1 more
Caused by: org.moqui.entity.EntityException: SQL Exception with statement:UPDATE STATUS_FLOW SET DESCRIPTION=?, LAST_UPDATED_STAMP=? WHERE STATUS_FLOW_ID=?; com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at org.moqui.impl.entity.EntityQueryBuilder.handleSqlException(EntityQueryBuilder.java:65) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityQueryBuilder.makePreparedStatement(EntityQueryBuilder.java:77) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityValueImpl.updateExtended(EntityValueImpl.java:153) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityValueBase.update(EntityValueBase.java:1329) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityValueBase.createOrUpdate(EntityValueBase.java:557) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.service.runner.EntityAutoServiceRunner.storeRecursive(EntityAutoServiceRunner.groovy:396) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.service.runner.EntityAutoServiceRunner.storeEntity(EntityAutoServiceRunner.groovy:352) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$LoadValueHandler.handlePlainMap(EntityDataLoaderImpl.groovy:415) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$EntityXmlHandler.endElement(EntityDataLoaderImpl.groovy:676) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195) ~[?:1.8.0_92]
	at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:298) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.doCall(EntityDataLoaderImpl.groovy:273) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.doCall(TransactionFacadeImpl.groovy:196) ~[moqui_temp7346945682760087828WEB-INF_lib_moqui-framework-2.0.0.jar.:2.0.0]
	... 1 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.

**Comment by jonesde** [comment] 2017-01-30 13:03
It looks like you're using version 5.1.5 of the MySQL JDBC driver... which is over 9 years old (looked real quick at the CHANGES file in a recent mysql-connector-java release). My guess is that is the cause of this issue. Try downloading the latest, or at least a much more recent, version of the driver.

**Comment by jonesde** [comment] 2017-02-01 15:35
No comments, appears to be an external issue and cannot reproduce. Closing.

**Closed by jonesde** 2017-02-01 15:35 UTC
