### ISSUE TITLE
Moqui can execute Javascript which request by user

### ISSUE THREAD

**Issue by fengbaicanhe** [moqui/moqui-framework#31] opened 2016-02-25 05:17 UTC
Today i tried some test to moqui-framework.

here is steps

1. run the framework and use Test Login button to login.
2. request `http://localhost:8080/apps/system/Security/UserAccount/UserAccountDetail?userId=EX_JOHN_DOE` (this works well)
3. request `http://localhost:8080/apps/system/Security/UserAccount/UserAccountDetail?userId=%3Cscript%3Ealert(%27Test%20Crack!%27);location.href=%27https://github.com/moqui/moqui-framework%27%3C/script%3E` (this replace userId param with javascript)
4. http://localhost:8080/apps/system/Security/UserAccount/UserAccountDetail?userId=EX_JOHN_DOE ( after step 3, request as step 2 again )
5. after step 4, you will see an alert dialog with message 'Test Crack!', and after click ok button,the browser will redirect to moqui-framework's github

this issue happens in other request ,such as :

- https://demo.moqui.org/apps/system/Security/UserGroup/UserGroupDetail?userGroupId=ADMIN
- https://demo.moqui.org/apps/system/Security/ArtifactGroup/ArtifactGroupDetail?artifactGroupId=ALL_SCREENS

moqui-framework version i tested is   master branch

the browser i use is chrome

**Comment by fengbaicanhe** [comment] 2016-02-25 06:33
sorry, other url's host is wrong, the  host is localhost, but i test this issue in demo.moqui.org,it occur too

**Comment by aabiabdallah** [comment] 2016-02-25 15:35
I didn't check the code but I believe the problem is in the navigation history which is not handling the parameters in a safe way.

**Comment by jonesde** [comment] 2016-02-26 18:44
The issue was with the screen history drop-down, which wasn't encoding the parameter values, as is done by default in most part of Moqui. This is fixed in commit #adc0fe9.

**Closed by jonesde** 2016-02-26 18:44 UTC
